### ISSUE TITLE
Supported Languages and Embedded Devices

### ISSUE THREAD

**Issue by vincedani** [ksasso1028/EasyOCR-cpp#12]
👋 I am currently searching a C++ version of the EasyOCR project, and I have some questions:

- I am curious that which languages are supported? I can see the English Gen2 only, furthermore, `lang/english_g2_characters.txt` contains non-english characters, so I'm not sure.
- Have you tried to run the project on a Raspberry Pi (for example)? Or on any other embedded (like) device?
- Did you compare the accuracy to the original Python module? Are there any bigger differences?

**Comment by ksasso1028** [comment]
Hello!

1. lang/english_g2_characters.txt is english, I would download the file and take a look, for some reason the raw on github shows chinese characters. only english at the moment, adding chinese and other languages should be simple, just havent had time to work on it. 
2. This project should run on a rasperry pi, or any device capable of compiling libtorch. You will need to build libtorch from source on your target device, since prebuilt binaries for arm are not distributed by pytorch. Havent done this in a while, so here is a tutorial on that https://qengineering.eu/install-pytorch-on-raspberry-pi-4.html
3. The models (text detection, and text recognition) are the same exact models, only running in C++. I ensured the outputs from the models were identical. The only differing factor is the bounding box merging algorithm, which EasyOCR implements in a custom way not related to the models. I chose to implement a merging algorithm which suited my needs. If you remove the merging from both repos, results will be the same.

**Comment by vincedani** [comment]
Thank you @ksasso1028 , your comment helped a lot. 

It's really interesting that the GitHub shows Chinese characters online, but yes, I have cloned the repository and locally I can see the english characters. 

Closing the issue as I got the answers.
