### ISSUE TITLE
dockerization

### ISSUE THREAD

**Issue by BBO-repo** [ksasso1028/EasyOCR-cpp#2]
Hello,
Thanks for your repo! You really did what you said [there](https://github.com/JaidedAI/EasyOCR/issues/709#issuecomment-1832995832).
Some suggestions that I have is that your repo is too much dependent on your local computer configuration, I thought a Dockerfile to play with your repo would be nice to have.
If you think it is valuable to add it I can add my Dockerfile, it automatically gets all dependencies: get libtorch and build latest OpenCV and build the application.

Also I've tried your code with get but got an error, seems that some tensor are in CPU while other are in GPU. Let's dig this point later
I would have some C++ specific comments on the code but let it for later, a [PR ](https://github.com/ksasso1028/EasyOCR-cpp/pull/1) was requested to solve a linux build.

**Comment by ksasso1028** [comment]
thank you for your comments and input !
RE: device pinned- because I had to  trace the model, the device is pinned to the device it was traced on. I can upload GPU pinned weights? I know it seems counterintuitive as it breaks the logic of the TorchModel class, which supports moving between devices with scripted models. I know it works on the CPU, so let me know if that is broken for you.  I can take a second look at scripting the models as that would allow the modularity of the TorchModel class.

RE:docker - this would be great ! I can add this as it seems important for others to get up speed, released this on a whim and certainly could use some cleaning up for production. 

Gonna take a look at your PR, thank you for your contribution and input !

**Comment by BBO-repo** [comment]
Hello,
No problem, happy to help on this topic!
If I can have it work properly on my machine I think I could go on helping in C++ code and C++ porting some other Python EasyOCR features in this repo after validating with you.

RE: docker, I'll send a PR soon.
RE: device pinned, can I add another issue to precisely address this, to avoid blurring the current discussion.

**Comment by ksasso1028** [comment]
Great, just merged your branch

**Comment by BBO-repo** [comment]
Hi,
I've added the [PR](https://github.com/ksasso1028/EasyOCR-cpp/pull/3) for dockerization.

**Comment by ksasso1028** [comment]
merged a bit ago, also added some changes to the decoding for better results, cheers
